# Breast Cancer Wisconsin with 5 clients and adaptive DP
seed: 42
dataset: "bcw"
model: "BCWDNN"  # Will need to be defined in model registry
data_dir: "./data"

# SFL Setup
num_clients: 5
batch_size: 16  # Smaller batch size for this small dataset
num_rounds: 20

# Model & Training
lr: 0.001
optimizer: "Adam"
cut_layer: 1  # Middle layer cut for the DNN model
min_acc: 0.1

# Data distribution
partition_method: "dirichlet"
dirichlet_alpha: 0.5  # moderate non-IID

# Differential Privacy Parameters (Adaptive noise parameters)
dp_noise:
  # Activation noise parameters
  activation_clip_norm: 1.0
  activation_noise_multiplier: 0.05  # Lower noise for activations
  
  # Gradient noise parameters
  clip_norm: 1.0
  initial_sigma: 0.05  # Lower initial noise
  
  # Mode and adaptive parameters
  mode: "unified"
  delta: 1e-5
  adaptive_clipping_factor: 0.9  # Enable adaptive clipping
  adaptive_noise_decay_factor: 0.9  # More aggressive adaptation
  noise_decay_patience: 2  # Reduced patience
  validation_set_ratio: 0.1

# Logging
log_interval: 2 