seed: 42
dataset: bcw
model: BCWDNN
data_dir: ./data
num_clients: 5
batch_size: 32
num_rounds: 20
lr: 0.005
optimizer: Adam
cut_layer: 3
min_acc: 0.1
partition_method: iid
dp_noise:
  activation_clip_norm: 1.0
  activation_noise_multiplier: 0.0
  clip_norm: 1.0
  initial_sigma: 0.0
  mode: unified
  delta: 1e-5
  adaptive_clipping_factor: 0.0
  adaptive_noise_decay_factor: 1.0
  noise_decay_patience: 0
  validation_set_ratio: 0.1
log_interval: 5 