# Experiment Configuration for central model (for comparison with split FL)
seed: 42
dataset: "MNIST"
model: "SimpleDNN" 
data_dir: "./data"

# SFL Setup - minimal values since we're simulating central training
num_clients: 1  # Single client
batch_size: 64
num_rounds: 1   # Just one round

# Model & Training - same as one_client for comparison
lr: 0.01
optimizer: "SGD"
cut_layer: 4  # Same as one_client for fair comparison
min_acc: 0.75  # Minimum required accuracy

# Differential Privacy Noise Parameters (Disabled for equivalence test)
dp_noise:
  # Laplacian Noise (Mechanism 1) - Disabled
  laplacian_sensitivity: 0.0
  epsilon_prime: 0.0
  
  # Gaussian Noise (Mechanism 2) - Disabled
  clip_norm: 1.0
  noise_multiplier: 0.0  # No noise
  delta: 1e-5
  
  # Adaptive Parameters (Disabled)
  adaptive_clipping_factor: 1.0
  initial_sigma: 0.0  # No noise
  adaptive_noise_decay_factor: 1.0
  noise_decay_patience: 0
  validation_set_ratio: 0.1

# Logging
log_interval: 1
