# Experiment Configuration (Fixed DP - CNN Model)
seed: 42
dataset: "MNIST"
model: "SimpleCNN"  # Use CNN model
data_dir: "./data"

# SFL Setup
num_clients: 10
batch_size: 64
num_rounds: 50

# Model & Training
lr: 0.01
optimizer: "SGD"  # Use SGD for DP compliance
cut_layer: 6  # After pool2, before flatten (indices: 0=conv1, 1=relu1, 2=pool1, 3=conv2, 4=relu2, 5=pool2, 6=flatten)

# Differential Privacy Noise Parameters (FIXED Gaussian)
dp_noise:
  laplacian_sensitivity: 0.0  # Laplacian disabled
  epsilon_prime: 1.0
  
  # Fixed Gaussian Parameters (Mechanism 2)
  clip_norm: 1.0             # Fixed clipping threshold
  noise_multiplier: 1.0      # Fixed noise scale (sigma)
  delta: 1e-5
  
  # Ensure adaptive parameters are not used or set to non-adaptive defaults
  adaptive_clipping_factor: 0.0  # Set to 0 to force use of initial clip_norm
  initial_sigma: 1.0            # This will be the fixed sigma used
  adaptive_noise_decay_factor: 1.0  # No decay
  noise_decay_patience: 1000  # Effectively disable decay trigger
  validation_set_ratio: 0.1  # Still need validation split for comparison run

# Logging
log_interval: 10 