# CNN with fast noise decay
seed: 42
dataset: "MNIST"
model: "SimpleCNN"
data_dir: "./data"

# SFL Setup
num_clients: 5
batch_size: 64
num_rounds: 20

# Model & Training
lr: 0.001  # Default learning rate for Adam
optimizer: "Adam"
cut_layer: 3  # Middle layer cut
min_acc: 0.1

# Differential Privacy Noise Parameters with fast decay
dp_noise:
  laplacian_sensitivity: 0.0
  epsilon_prime: 1.0
  clip_norm: 1.0
  noise_multiplier: 0.5  # Medium noise
  delta: 1e-5
  adaptive_clipping_factor: 1.0
  initial_sigma: 0.5  # Medium noise
  adaptive_noise_decay_factor: 0.9  # Fast decay (0.9 instead of 0.99)
  noise_decay_patience: 1  # More aggressive adaptation
  validation_set_ratio: 0.1

# Logging
log_interval: 5
