# Experiment Configuration (Fixed DP - DNN Model)
seed: 42
dataset: "MNIST"
model: "SimpleDNN"
data_dir: "./data"

# SFL Setup
num_clients: 10
batch_size: 64
num_rounds: 50

# Model & Training
lr: 0.01
optimizer: "Adam"
cut_layer: 4

# Differential Privacy Noise Parameters (FIXED Gaussian)
dp_noise:
  laplacian_sensitivity: 0.0 # Laplacian disabled
  epsilon_prime: 1.0
  
  # Fixed Gaussian Parameters (Mechanism 2)
  clip_norm: 1.0             # Fixed clipping threshold
  noise_multiplier: 1.0      # Fixed noise scale (sigma)
  delta: 1e-5
  
  # Ensure adaptive parameters are not used or set to non-adaptive defaults if read by adaptive code
  adaptive_clipping_factor: 0.0 # Set to 0 to force use of initial clip_norm
  initial_sigma: 1.0            # This will be the fixed sigma used
  adaptive_noise_decay_factor: 1.0 # No decay
  noise_decay_patience: 1000 # Effectively disable decay trigger
  validation_set_ratio: 0.1 # Still need validation split for comparison run

# Logging
log_interval: 10 