# Experiment Configuration (No DP Noise)
seed: 42
dataset: "MNIST"
model: "SimpleCNN"
data_dir: "./data"

# SFL Setup
num_clients: 10
batch_size: 64
num_rounds: 10 # Reduced rounds

# Model & Training
lr: 0.01
optimizer: "Adam"
cut_layer: 4

# Differential Privacy Noise Parameters (DISABLED)
dp_noise:
  laplacian_sensitivity: 0.0 # Laplacian disabled
  epsilon_prime: 1.0

  # Parameters for Gaussian noise on gradients (Mechanism 2)
  clip_norm: 1.0             # Clipping value (doesn't affect outcome when noise_multiplier=0)
  noise_multiplier: 0.0      # Gaussian disabled
  delta: 1e-5

# Logging
log_interval: 10 # Log training loss every N rounds 