# Experiment Configuration (No DP Noise)
seed: 42
dataset: "MNIST"
model: "SimpleCNN"
data_dir: "./data"

# SFL Setup
num_clients: 1
batch_size: 64
num_rounds: 5 # Reduced rounds for quicker comparison

# Model & Training
lr: 0.01
optimizer: "SGD" # Options: SGD, Adam
cut_layer: 0 # Index for splitting SimpleCNN (after flatten)
            # 0: conv1, 1: relu1, 2: pool1, 3: conv2, 4: relu2, 5: pool2, 6: flatten, 7: fc1, 8: relu3, 9: fc2

# Differential Privacy Noise Parameters (DISABLED)
dp_noise:
  laplacian_sensitivity: 0.0 # Set to 0 to disable Laplacian noise
  epsilon_prime: 1.0         # Value doesn't matter when sensitivity is 0

  # Parameters for Gaussian noise on gradients (Mechanism 2)
  clip_norm: 100.0             # Clipping still happens, but noise is disabled
  noise_multiplier: 0.0      # Set to 0 to disable Gaussian noise
  delta: 1e-5                # Value doesn't matter when noise_multiplier is 0

# Logging
log_interval: 10 # Log training loss every N rounds 